version: 0.0
os: linux

files:
    - source: /
      destination: /home/ubuntu/LetMeKnow
      overwrite: yes

permissions:
    - object: /
      pattern: "**"
      owner: ubuntu
      group: ubuntu
      mode: 755
      type:
        - file
        - directory

hooks:
    AfterInstall:
        - location: scripts/deploy.sh
          timeout: 300
          runas: ubuntu



