version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/LetMeKnow
    overwrite: yes

permissions:
  - object: /home/ubuntu/LetMeKnow
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
