# local
spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: jdbc:mysql://${MY_SQL.HOST}:${MY_SQL.PORT}/${MY_SQL.DATABASE}?useSSL=false&serverTimezone=Asia/Seoul
        username: ${DB.USERNAME}
        password: ${DB.PASSWORD}

    jpa:
        hibernate:
            ddl-auto: ${JPA.DDL_AUTO}

# JWT
jwt:
    token:
        access:
            expiration: 86_400_000 # 1일
