# prod
spring:
    config:
        import: 'aws-parameterstore:'
        activate:
            on-profile: prod
    datasource:
        url: jdbc:mysql://${MY_SQL.HOST}:${MY_SQL.PORT}/${MY_SQL.DATABASE}?useSSL=false&serverTimezone=Asia/Seoul
        username: ${DB.USERNAME}
        password: ${DB.PASSWORD}

    jpa:
        hibernate:
            ddl-auto: ${JPA.DDL_AUTO}

# JWT
jwt:
    token:
        access:
            expiration: 300000 # 5분

# SQL log
logging:
    level:
        p6spy: DEBUG

decorator:
    datasource:
        p6spy:
            enable-logging: false
# SQL log

# cors
allowed-origin: ${DOMAIN}
# cors

# domain
domain: ${DOMAIN}
