# prod
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: jdbc:mysql://localhost:3306/letmeknow?useSSL=false&serverTimezone=Asia/Seoul
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: create

# JWT
jwt:
    token:
        access:
            expiration: 300000 # 5분
