# This is a basic workflow to help you get started with Actions

name: LetMeKnow

# Controls when the workflow will run
on:
  # 지정한 branch에서 push/pull_request에 해당하는 command가 수행되면 이 workflow가 동작 합니다. 
  # 여기서는 간단히 main 브런치에서 push되면서 이 workflow가 실행 되도록 하겠습니다.
  pull_request:
    branches: [ main ]
 
  # 이부분은 위의 trigger가 없어도 수동으로 동작 할 수 있게끔 해주는 역할을 합니다.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" 
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout release
      uses: actions/checkout@v3

    # Runs a single command using the runners shell 
    - name: Clean temp directory
      run: |
        rm -rf *
        cp -r $GITHUB_WORKSPACE . 
      
    - name: archive LetMeKnow
      run: tar cvfz ./LetMeKnow.tar.gz *
       
    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-2
        
    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./LetMeKnow.tar.gz s3://letmeknow/archive/
      
    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name LetMeKnow
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name LetMeKnow
        --s3-location bucket=letmeknow,bundleType=tgz,key=archive/LetMeKnow.tar.gz
